# Generated by Django 3.1.6 on 2021-02-20 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Subject',
            new_name='subject',
        ),
    ]
