# Generated by Django 3.1.6 on 2021-02-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.ImageField(upload_to='media/technologies/'),
        ),
    ]
