# Generated by Django 3.1.6 on 2021-02-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20210220_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_development',
            field=models.BooleanField(default=True),
        ),
    ]
