# Generated by Django 3.1.6 on 2021-03-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20210302_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='score',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='work_hours',
            field=models.FloatField(blank=True),
        ),
    ]
