# Generated by Django 3.1.6 on 2021-03-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20210302_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='work_hours',
            field=models.FloatField(default=0),
        ),
    ]
