# Generated by Django 3.1.6 on 2021-03-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_auto_20210305_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='staff_position',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
