# Generated by Django 3.1.6 on 2021-03-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20210218_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='picture',
            field=models.ImageField(blank=True, upload_to='teamMember/'),
        ),
    ]
