# Generated by Django 3.1.6 on 2021-03-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wolfdiary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wolfpage',
            name='image',
            field=models.ImageField(upload_to='wolf-diary'),
        ),
    ]
